runtime: python310
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind :$PORT sql_app.main:app

service: testing

instance_class: F2

env_variables:
  DATABASE_URL: "postgresql://user:$bgJ2hFlZ4$dV5mN@34.68.149.174:5432/postgres"