runtime: python310
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind :$PORT sql_app.main:app

service: default

instance_class: F2

env_variables:
  DATABASE_URL: "postgresql://postgres:appengine_demo@35.197.150.193/todo"