runtime: python310
entrypoint: uvicorn main:app --port $PORT --workers 4

service: default

instance_class: F2

env_variables:
  DATABASE_URL: "postgresql://postgres:appengine_demo@35.197.150.193/todo"

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto