name: Deploy on Commit
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: 'ubuntu-20.04'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate Google App Engine
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Google App Engine
      uses: google-github-actions/deploy-appengine@v0
      with:
        deliverables: app.yaml
